# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-15 04:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='abono',
            name='abono_id',
        ),
        migrations.RemoveField(
            model_name='cartera',
            name='cartera_id',
        ),
        migrations.RemoveField(
            model_name='venta',
            name='venta_id',
        ),
    ]
