# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-15 16:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0003_venta_cantidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='cedula',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
